name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: ['*', '!update-*-to-*', '!IBC-update*']
    tags-ignore:
      - 'v*'
  pull_request:
    branches: ['master']

jobs:
  build:
      name: Build image
      strategy:
        fail-fast: false
        matrix:
          channel: ['stable', 'latest']
      uses: ./.github/workflows/build.yml
      with:
          channel: ${{ matrix.channel }}
